import Head from "next/head";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import HomePage from "@/components/HomePage";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>samarithan | WhatsApp ChatBot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={inter.className}>
        <div className="min-h-screen flex flex-col">
          {/* hHomePage */}
          <HomePage />
          {/* main */}
          <Footer />
        </div>
      </div>
    </div>
  );
}
